info:
  app:
    name: irctc
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9090
spring:
  application:
    name: irctc
    
logging:
  level:
    root: error
    com.bishwa: debug

    
